### ISSUE TITLE
Add missing swagger UI options

### ISSUE THREAD

**Issue by xC0dex** [xC0dex/APIWeaver#11]
## Description
The `SwaggerUiOptions` class in `src/APIWeaver.Swagger/Models/SwaggerUiOptions.cs` currently does not include all the options available in the Swagger UI configuration, as per the [Swagger UI Configuration Documentation](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md).

## Scope of the Task
Add the following missing options to the `SwaggerUiOptions` class:

- `DocExpansion`
- `Filter`

## Not scope of the task
- `OperationsSorter`
- `TagsSorter`
-  `Presets`
- `Plugins`
- `SupportedSubmitMethods`
- `ShowMutatedRequest`
- `WithCredentials`
- `RequestInterceptor`
- `ResponseInterceptor`
- `ModelPropertyMacro`
- `ParameterMacro`

**Comment by Elektrotech** [comment]
wichtig
